name: stevenbeardsley
favicon: null
layout_spectrum: 0.5409219334833324
typography_spectrum: 0.4740118633490056
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.21529929316602647
  lightness: 0.5699690433684736
  saturation: 0.327985247829929
  rhythmicContrast: 0.8094360020477325
purpose: []
